apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.14.1
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.roles: ["master"]
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.io/elasticsearch:8.14.1
  - name: data-nodes
    count: 2
    config:
      node.roles: ["data"]
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.io/elasticsearch:8.14.1
  - name: client-nodes
    count: 2
    config:
      node.roles: ["ingest"]
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.io/elasticsearch:8.14.1