apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
config:
  xpack.fleet.packages:
  - name: apm
    version: latest
spec:
  version: 8.14.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system
