apiVersion: v1
kind: Service
config:
  xpack.fleet.packages:
  - name: apm
    version: latest
metadata:
  creationTimestamp: null
  labels:
    app: kibana
  name: kibana
  namespace: elastic-system
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  type: NodePort
