apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic
  namespace: elastic-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: Immediate